# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
minecraft_version=1.21.4
loader_version=0.16.10
loom_version=1.9-SNAPSHOT

# Mod Properties
version=1.0.0
group=com.vailen

# Dependencies
fabric_api_version=0.114.0+1.21.4
